const CO_COLORS=[['Ameixa','#531B44'],['Ameixa-escuro','#471839'],['Âmbar','#F5A23B'],['Dourado','#EA9436'],['Laranja','#E67F42'],['Verde','#00AE77'],['Verde-petróleo','#006161'],['Rosa','#EB234E'],['Magenta','#AC024F'],['Coral','#FC4D32'],['Vermelho','#DA2821'],['Vermelhão','#FF361A'],['Areia','#E5CCB2']];
const CO_ART=['Brinde','Coração do Brasil','Árvore do Cerrado','Chopeira','Bússola','Binóculos'];
const CO_WEIGHTS=[['Thin',100],['ExtraLight',200],['Light',300],['Regular',400],['Medium',500],['SemiBold',600],['Bold',700],['ExtraBold',800],['Black',900]];
const coAsset=name=>`../assets/colombina-${name}.svg`;
function coDownload(name,label){return `<a class="utility small" href="${coAsset(name)}" download="colombina-${name}.svg" aria-label="Baixar ${escapeHtml(label)} em SVG">${icon('download',16)}SVG</a>`;}
function coArt(){return `<div class="graphics-grid illustration-grid">${CO_ART.map((label,i)=>`<article class="graphic-card"><div class="graphic-stage"><img src="${coAsset('ilustracao-'+(i+1))}" alt="${label}" width="200" height="200" loading="lazy"></div><div class="panel-footer"><span>${label}</span>${coDownload('ilustracao-'+(i+1),label)}</div></article>`).join('')}</div>`;}
function coColorInk(hex){const c=hex.slice(1).match(/../g).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);const l=c[0]*.2126+c[1]*.7152+c[2]*.0722;return (l+.05)/.05>1.05/(l+.05)?'#000':'#fff';}
PAGES['visao-geral']=()=>`
 <section class="colombina-hero"><div><span class="brand-kicker">A cerveja do Cerrado</span><h2>A vida merece<br>um brinde.</h2><p>Uma identidade com origem, personalidade e cor em cada encontro.</p><a href="#identidade" class="hero-link">Conhecer a identidade ${icon('arrow-up-right',18)}</a></div><div class="hero-art"><img src="../assets/colombina-selo.svg" alt="Colombina — A cerveja do Cerrado" width="850" height="849"></div></section>
 ${sectionHeading('Explore o Design System')}
 <div class="foundation-row"><a class="foundation-card" href="#cores"><div><h3>Cores</h3><p>13 cores da Colombina.</p><div class="mini-palette">${['#531B44','#F5A23B','#E67F42','#00AE77','#AC024F','#E5CCB2'].map(c=>`<i style="background:${c}"></i>`).join('')}</div></div>${icon('arrow-up-right',20)}</a><a class="foundation-card" href="#tipografia"><div><h3>Tipografia</h3><p>Blimone + Inter</p><span class="type-preview type-brand">Aa Bb Cc</span></div>${icon('arrow-up-right',20)}</a></div>
 ${sectionHeading('Componentes')}
 <div class="component-index">${PAGE_DEFINITIONS.filter(page=>page.group==='Componentes').map(page=>`<a href="#${page.id}" class="index-card"><span class="index-icon">${icon(page.icon,22)}</span><strong>${page.label}</strong><p>${['inputs','text-field','textarea'].includes(page.id)?'7 estados':page.id==='botoes'?'3 variações · 5 estados':page.id==='alertas'?'5 variações':'Variações e exemplos'}</p><span class="arrow">${icon('arrow-up-right',16)}</span></a>`).join('')}</div>
 <a class="icon-feature" href="#icones"><span class="feature-glyphs">${['utensils','users','compass','sprout','workflow','route'].map(id=>icon(id,27)).join('')}</span><div><h2>Banco de ícones</h2><p>447 ícones · 24 categorias</p></div><span class="feature-arrow">${icon('arrow-up-right',24)}</span></a>
 ${sectionHeading('Ilustrações da marca')}${coArt()}`;
PAGES.identidade=()=>`
 ${sectionHeading('Logotipos')}
 <div class="graphics-grid">${[['Branco',1],['Ameixa',2]].map(([label,n])=>`<article class="graphic-card"><div class="graphic-stage logo ${n===1?'dark':''}"><img src="${coAsset('logo-'+n)}" alt="Colombina — logotipo ${label.toLowerCase()}" width="899" height="384"></div><div class="panel-footer"><span>${label}</span>${coDownload('logo-'+n,'logotipo '+label.toLowerCase())}</div></article>`).join('')}</div>
 ${sectionHeading('Selo da marca')}
 <article class="graphic-card"><div class="seal-stage"><img src="../assets/colombina-selo.svg" alt="A cerveja do Cerrado" width="850" height="849"></div><div class="panel-footer"><span>A cerveja do Cerrado</span>${coDownload('selo','selo da marca')}</div></article>
 ${sectionHeading('Ilustrações')}${coArt()}`;
PAGES.cores=()=>`
 ${sectionHeading('Paleta da marca')}
 <div class="brand-swatches">${CO_COLORS.map(([name,c])=>`<article class="brand-swatch"><div class="color-block" style="background:${c};color:${coColorInk(c)}"><span>Aa</span></div><div class="swatch-text"><strong>${name}</strong><button type="button" data-action="copy-color" data-color="${c}" aria-label="Copiar ${c}">${c}${icon('copy',14)}</button></div></article>`).join('')}</div>
 ${sectionHeading('Combinações')}
 <div class="color-combinations"><div style="background:#531b44;color:#fff"><span>A vida merece um brinde.</span><p>Ameixa + branco</p><img src="../assets/colombina-ilustracao-1.svg" alt=""></div><div style="background:#f5a23b;color:#471839"><span>Encontros com sabor.</span><p>Âmbar + ameixa-escuro</p><img src="../assets/colombina-logo-2.svg" alt="Colombina"></div><div style="background:#e5ccb2;color:#531b44"><span>Feita de Cerrado.</span><p>Areia + ameixa</p><img src="../assets/colombina-logo-2.svg" alt="Colombina"></div></div>`;
PAGES.tipografia=()=>`
 <section class="type-hero"><div><span class="eyebrow">Famílias tipográficas</span><h2>Blimone + Inter</h2><p>Personalidade nos títulos. Clareza na interface.</p></div><span class="type-hero-aa" aria-hidden="true">Aa</span></section>
 <div class="font-pair"><article><span class="eyebrow">Títulos e destaques</span><h3>Blimone</h3><p>Todos os pesos da família, conforme os arquivos da marca.</p></article><article><span class="eyebrow">Textos e controles</span><h3 class="inter-title">Inter</h3><p>100–900 · normal e itálico.</p></article></div>
 <p class="type-status">Blimone usa a fonte instalada no dispositivo; enquanto seus arquivos não forem incorporados, a prévia usa Inter como apoio.</p>
 ${panel('Experimente a tipografia',`<div class="specimen-controls"><label>Família<select id="co-font" data-co-type><option value="Inter">Inter</option><option value="Blimone">Blimone</option></select></label><label>Peso<select id="co-weight" data-co-type>${CO_WEIGHTS.map(([name,w])=>`<option value="${w}" ${w===400?'selected':''}>${w} · ${name}</option>`).join('')}</select></label><label>Estilo<select id="co-style" data-co-type><option value="normal">Normal</option><option value="italic">Itálico</option></select></label><label>Tamanho <output id="co-size-label">36 px</output><input id="co-size" data-co-type type="range" min="18" max="64" value="36" aria-label="Tamanho da prévia"></label></div><div class="specimen-preview" id="co-preview">A vida merece um brinde.</div><div class="specimen-entry"><label for="co-text">Texto da prévia</label><input id="co-text" data-co-type value="A vida merece um brinde." maxlength="180"></div>`)}
 ${sectionHeading('Inter · todos os pesos')}<div class="weight-grid">${CO_WEIGHTS.map(([name,w])=>`<div><span style="font-weight:${w}">Ag</span><p>${name} · ${w}</p></div>`).join('')}</div>
 ${sectionHeading('Caracteres')}${panel('Inter',`<div class="font-specimen"><p class="alphabet">ABCDEFGHIJKLMNOPQRSTUVWXYZ<br>abcdefghijklmnopqrstuvwxyz</p><p class="digits">0123456789 &amp; @ # À Á Â Ã Ç É Ê Í Ó Ô Õ Ú</p></div>`)}
 ${sectionHeading('Hierarquia')}<div class="type-scale">${[['Título','A vida merece um brinde.',36,700,'Blimone'],['Subtítulo','A cerveja do Cerrado.',23,600,'Blimone'],['Corpo de texto','Histórias, sabores e encontros que merecem ser compartilhados.',16,400,'Inter'],['Rótulo','Nome da campanha',14,500,'Inter'],['Texto auxiliar','Informe um nome válido.',12,400,'Inter']].map(([label,text,size,weight,family])=>`<div><span class="scale-label">${label} · ${family}</span><p style="font-family:${family},Inter,sans-serif;font-size:${size}px;font-weight:${weight}">${text}</p></div>`).join('')}</div>`;
function coUpdateType(){const preview=document.getElementById('co-preview');if(!preview)return;const family=document.getElementById('co-font').value==='Blimone'?'Blimone':'Inter';const weight=document.getElementById('co-weight');const style=document.getElementById('co-style');const isBrand=family==='Blimone';weight.disabled=isBrand;style.disabled=isBrand;preview.style.fontFamily=family+',Inter,sans-serif';preview.style.fontWeight=isBrand?'400':weight.value;preview.style.fontStyle=isBrand?'normal':style.value;const size=Math.max(18,Math.min(64,Number(document.getElementById('co-size').value)||36));preview.style.fontSize=size+'px';document.getElementById('co-size-label').textContent=size+' px';preview.textContent=document.getElementById('co-text').value||'A vida merece um brinde.';}
document.addEventListener('input',event=>{if(event.target.matches?.('[data-co-type]'))coUpdateType();});
document.addEventListener('change',event=>{if(event.target.matches?.('[data-co-type]'))coUpdateType();});
document.addEventListener('click',async event=>{const target=event.target.closest?.('[data-action="copy-color"]');if(!target)return;const value=target.dataset.color;try{await navigator.clipboard.writeText(value);notify('Cor copiada: '+value);}catch(_){const area=document.getElementById('copy-content');area.value=value;document.getElementById('copy-title').textContent='Copiar cor';document.getElementById('copy-dialog').showModal();area.focus();area.select();}});
